### ISSUE TITLE
"Last day of month" recurrence

### ISSUE THREAD

**Issue by gennaroanesi** [django-recurrence/django-recurrence#112]
Is it possible to create a "Every last day of month" rule using the current implementation?
I wanted to create a recurrence like

``class.recurrences = recurrence.Recurrence(
    dtstart=timezone.make_aware(datetime(2018, 1, 1, 12, 0, 0)),
    rrules=[recurrence.Rule(recurrence.LAST_DAY_OF_MONTH), ]
)``

so my occurrences are
2018-01-31
2018-02-28
2018-03-31
...

starting with the "first last day of month" after the start date for the recurrence.

**Comment by anomitra** [comment]
I think this can be achieved by the following rulestring.
`FREQ=MONTHLY;BYMONTHDAY=28,29,30,31;BYSETPOS=-1`
