### ISSUE TITLE
django 2 compatibility: TypeError: "on_delete"

### ISSUE THREAD

**Issue by jcuotpc** [django-recurrence/django-recurrence#115]
When running under django 2 I get the following error:
```
  File "/../.virtualenvs/dj-registrations/lib/python3.6/site-packages/recurrence/models.py", line 18, in Rule
    recurrence = models.ForeignKey(Recurrence, related_name='rules')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by aclark4life** [comment]
@jcuotpc FYI this is not a django-recurrence issue… from https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0 "The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update."

**Comment by craigsander** [comment]
Any word on whether and when this will get Django 2.0 support? Anything the community can do to help?

**Comment by oliwarner** [comment]
@aclark4life In my case anyway it was more that the copy on pypi.org is ancient (from Oct 2017) so hasn't had these upgrades yet.

@craigsander the master branch supports Django 2 but may not be otherwise ready for consumption. You can try it with:

    pip install -U git+git://github.com/django-recurrence/django-recurrence.git#egg=django-recurrence

**Comment by dominicrodger** [comment]
Paging @emperorcezar - I think we're safe to push a 1.6.0 to PyPI at this point - it'd just require the release notes being updated, and references to 1.5.0 in the source (e.g. setup.py).

**Comment by dominicrodger** [comment]
New release pushed, closing.
