### ISSUE TITLE
Django-2.0 support

### ISSUE THREAD

**Issue by pobk** [django-recurrence/django-recurrence#120]
Recurrence does not currently support Django 2.0 and throws an exception to the lack of on_delete parameter for the field.

  File "/Users/Richard/projects/nuvias/.venv/lib/python3.6/site-packages/recurrence/models.py", line 17, in <module>
    class Rule(models.Model):
  File "/Users/Richard/projects/nuvias/.venv/lib/python3.6/site-packages/recurrence/models.py", line 18, in Rule
    recurrence = models.ForeignKey(Recurrence, related_name='rules')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by dominicrodger** [comment]
This was fixed by #110 - we just don't have a new enough release on PyPI. Paging @emperorcezar - can you push a new release?

**Comment by dominicrodger** [comment]
@emperorcezar  - guessing life is busy for you at the moment - any chance you can give me permissions to push PyPI releases? I'm dominicrodger on PyPI.

**Comment by emperorcezar** [comment]
Of course, and actually, this got accidentally filtered in my email. I'll
push later today.

**Comment by emperorcezar** [comment]
Pushed. Had issues with twine crashing, but all good now.

**Comment by dominicrodger** [comment]
Thanks @emperorcezar. Marking closed. @pobk - take a look, feel free to open new issues if you see problems.
