### ISSUE TITLE
ReferenceError: recurrence is not defined

### ISSUE THREAD

**Issue by yahiaali** [django-recurrence/django-recurrence#121]
I'm trying to get `django-recurrence` up and running with a Django 2.0 project and I'm having trouble rendering the recurrence widget. I've started a very basic Django project to demonstrate the issue here: https://github.com/yahiaali/django-recurrence-demo/tree/freeze-6.25.2018

Running this project and going to `localhost:8000` results in the following:
<img width="711" alt="screen shot 2018-06-25 at 4 24 57 pm" src="https://user-images.githubusercontent.com/24771105/41874005-a09b1f08-7894-11e8-80cf-a9505b53b301.png">

The generated source code for this page is as follows:
```
<form method="POST" class="post-form">
    <input type='hidden' name='csrfmiddlewaretoken' value='o1OeOMQdbwHADsdwOPGHY2sGIdlGWudjB7pXl4HEYsIJUyCoBrSlwQ7yUDInLE9X' />
    
    <tr><th><label for="id_title">Title:</label></th><td><input type="text" name="title" maxlength="200" required id="id_title" /></td></tr>
<tr><th><label for="id_recurrences">Recurrences:</label></th><td><textarea name="recurrences" cols="40" rows="10" class="recurrence-widget" required id="id_recurrences">
</textarea>
<script type="text/javascript">recurrence.language_code ='en-us';new recurrence.widget.Widget('id_recurrences', {});</script></td></tr>
    <button type="submit">Submit</button>
</form>
```
And it's corresponding Django template is here: https://github.com/yahiaali/django-recurrence-demo/blob/freeze-6.25.2018/testapp/templates/test_form.html

As far as I can tell, I have correctly completed the installation steps outlined in the [tutorial](https://django-recurrence.readthedocs.io/en/latest/index.html). Has anyone else encountered this issue before?

**Comment by GriceTurrble** [comment]
Looking over the install instructions, you may have missed the static file configuration, which is causing `{{ form.media }}` to output nothing.

Try running `python manage.py collectstatic`, restart the server, and then see if it works.

**Comment by yahiaali** [comment]
Thanks @GriceTurrble. I ran that during installation, but, just to be sure, here's the output when I run it again:
```
0 static files copied to 'path/to/django-recurre
nce-demo/static', 122 unmodified.
```
My static directory is located [here](https://github.com/yahiaali/django-recurrence-demo/tree/freeze-6.25.2018/static) if that helps.

**Comment by yahiaali** [comment]
Update: I was able to resolve this error by manually adding the paths to the required Javascript and CSS files to the `Media` class in my model form.
```
class CourseForm(forms.ModelForm):
    ...
    class Media:
        js = ('recurrence/js/recurrence.js',
              'recurrence/js/recurrence-widget.js')
        css = {
            'all': ('recurrence/css/recurrence.css',)
        }
```
Working code posted here: https://github.com/yahiaali/django-recurrence-demo/tree/master
