### ISSUE TITLE
Django 2.0 support.

### ISSUE THREAD

**Issue by shayneoneill** [django-recurrence/django-recurrence#127]
I see there was a closed Django 2.0 support ticket regarding issues around, the ReccurenceField. I don't believe it is completely fixed however. 

I'm using 1.6, which is the last pushed to PyPi, on Django 2.0.8, using a CreateView and a Form. It all works great until I need to serialize the model into JSON when I get;-

**AttributeError: 'RecurrenceField' object has no attribute '_get_val_from_obj'
**

whilst trying to serialize the model. Even with a custom encoder with a handler for the type, django still attempts to call this for some reason. 

I've located the problem to this line;-

    def value_to_string(self, obj):
        return self.get_prep_value(self._get_val_from_obj(obj))

_get_val_from_object() has been removed from Django  and replaced with value_from_object() for reasons I can't discern. I think this would need to be patched around perhaps with a version check to ensure the correct call is made. For now however, recurrence fields appear to be unserializable without manually patching the library.

**Comment by dominicrodger** [comment]
Hey @shayneoneill,

There are further fixes in 1.7.0 (see [the docs](https://django-recurrence.readthedocs.io/en/latest/changelog.html), which hasn't been pushed yet (I think #126 has the relevant fix for the problem you're having).

Could you try installing from GitHub directly, and confirm everything's working as expected? If so, we can look at pushing a new release to PyPI.

Dom

**Comment by shayneoneill** [comment]
Yep. That does the tricks. Its all looking good from here Captain.

Oh and neat discovery. I didn't expect this, but it plays nice with crispy forms. I thought that was gonna be a pain point, but apparently not!

Thanks for your work!

**Comment by pasevin** [comment]
Hey, any progress on this?

**Comment by dominicrodger** [comment]
Whoops, forgot to close this - we pushed 1.7.0 quite a while back, and we've  fixed up more minor issues with Django 2.0 in subsequent releases.

Django 2.0 should be supported with recent versions of django-recurrence. If you're seeing problems let's start a new ticket.
