### ISSUE TITLE
No widget in admin

### ISSUE THREAD

**Issue by scwall** [django-recurrence/django-recurrence#128]
hello, i not widget in administration django
 I use in models.py:
![image](https://user-images.githubusercontent.com/30811539/45644049-ed245780-babc-11e8-866e-6ded076f8853.png)
and admin.py:
![image](https://user-images.githubusercontent.com/30811539/45644079-01685480-babd-11e8-9092-12e420a7e105.png)
but, I do not have the widget like this :
![image](https://user-images.githubusercontent.com/30811539/45644016-cebe5c00-babc-11e8-973e-2ac3e329cc37.png)
I have : 
![image](https://user-images.githubusercontent.com/30811539/45644144-3ecce200-babd-11e8-838a-03937f4ab844.png)

I'm new to django and I'm trying to understand how I can add more libraries. thank you in advance for your response

**Comment by uroybd** [comment]
I'm also having the same problem.

**Comment by pm8k** [comment]
I am also having the same trouble in the newer python/django.

In python=3.5.6 and django=1.11.10, I am able to see the widget in admin.

However, using python=3.7.0 and django=2.1 or django=2.0.5, I get the same blank field viewed above. 

I have attempted all the installation instructions in the docs, which helped me get setup in 3.5.6, but no luck with the newest version of python and django.

**Comment by sww314** [comment]
I am having the same problem. 

Debugging on the JS side, the libraries are not getting loaded. 
Looks like the issues is that the `javascript_catalog()` views was removed. This makes the `find_recurrence_i18n_js_catalog()` fail.

**Comment by sww314** [comment]
Here is how I fixed it (for Django 2.0 also should work for 2.1)
These changes to the package: https://github.com/sww314/django-recurrence/commit/6942506c72e5f55f778be1d9d8000b61b52639da

Then in settings.py: 
`RECURRENCE_I18N_URL = "javascript-catalog" # Name of URL to use`
And in urls.py:
  ```
  # Add JS libraries to make recurrence widget work
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['recurrence']), name="javascript-catalog"),
```
Documentation for context:
https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#module-django.views.i18n

**Comment by alantrick** [comment]
The problem is that `find_recurrence_i18n_js_catalog` fails with an ImportError on django 2. The following works as a workaround in your urls.py:

```
js_info_dict = {
    'packages': ('recurrence', ),
}

# jsi18n can be anything you like here
urlpatterns += [
    path('jsi18n/', django.views.i18n.JavaScriptCatalog.as_view(
        packages=['recurrence']), name="javascript-catalog"),
]
# monkey patch workaround for bug in recurrence library
django.views.i18n.javascript_catalog = None```

**Comment by scwall** [comment]
Thanks for all responses :).
I do not have time yet to test all this, I'll do it shortly and I'll keep you informed
