### ISSUE TITLE
Proposal: drop Python 2.x support on next release

### ISSUE THREAD

**Issue by aleksihakli** [django-recurrence/django-recurrence#144]
As we're migrating Django projects into Django 2.x, some old APIs are becoming unavailable in the latest master release. 

Would it be feasible to drop Python 2.7 support in the next django-recurrence release as December and the Python 2.7 deprecation is coming soon? This would enable cleaner, Python 3 only code.

I have personally been advocating for Python 3.6+ code for Django projects, as running on Python 3.6 or newer offers f-strings, ordered dicts, and other nice features for projects and enables the deprecation of a lot of legacy stuff, making codebases cleaner and faster to develop.

This proposal stems from a project where we're depending on django-recurrence and where builds fail for Django master that deprecates the [`python_2_unicode_compatible`](https://github.com/django-recurrence/django-recurrence/blob/07add25c01058206d3e273598c8716d8d31c47e8/recurrence/base.py#L19) API that is used by django-recurrence in.

**Comment by dominicrodger** [comment]
That sounds fine to me - any pull request welcome here. We'd do a minor version bump for this, obviously.

**Comment by aleksihakli** [comment]
Great! I'll try and make a PR that cleans up the old Python 2 stuff up a bit. I just opened one for the related [django-ical project update](https://github.com/jazzband/django-ical/pull/29), is a similar PR OK?

**Comment by dominicrodger** [comment]
This was merged in #145 - I'll update release notes and push django-recurrence 1.10.0 shortly.
