### ISSUE TITLE
Form not displaying

### ISSUE THREAD

**Issue by chinochao** [django-recurrence/django-recurrence#153]
I am using the following versions.

Django==2.2.5
django-recurrence==1.10.1
Python 3.7.4

However in my form it seems to only show Add Rule and Add Date but they do not do anything when I click on them. I followed the instructions at https://django-recurrence.readthedocs.io/en/latest/installation.html#install for the installation and setup the model and form. I am also using Generic Views if that helps.

**Comment by chinochao** [comment]
Turns out I am getting Javascript errors.

ReferenceError: pgettext is not defined
recurrence.js:1038:5
    <anonymous> http://127.0.0.1:8000/static/recurrence/js/recurrence.js:1038
TypeError: Argument 1 of MutationObserver.observe is not an object.recurrence-widget.init.js:7:11
    <anonymous> http://127.0.0.1:8000/static/recurrence/js/recurrence-widget.init.js:7
    jQuery 2

**Comment by chinochao** [comment]
It seemed the issue was related to the javascript catalog.

I added the following to my urls.py

# jsi18n can be anything you like here
urlpatterns += [
    path('jsi18n.js', JavaScriptCatalog.as_view(packages=['recurrence']), name='jsi18n'),
]

And on my base.html I added the following on the header.

  <script src="{% url 'jsi18n' %}"></script>

**Comment by pedrofaria09** [comment]
Hello,
Im with a problem using recurrence and autocomplete at the same time.
My page is divided in 2 forms:
1st form- containing autocomplete, datepicker, etc.
2nd form- containing recurrence and MultiSelectField.
When I comment {{ form2.media }}, I got autocomplete working but recurrence doesn't work:
![Captura de ecrã 2021-08-13, às 15 13 21](https://user-images.githubusercontent.com/14875822/129370884-579c7e43-4ca8-402f-bc6f-efeae6b1fa7d.png)

When I use {{ form2.media }}, recurrence works, but autocomplete doesn't:
![Captura de ecrã 2021-08-13, às 15 14 05](https://user-images.githubusercontent.com/14875822/129370900-e04b34ad-6778-499f-a260-648adb521e51.png)

If I use the recurrence in 1st form, neither autocomplete and datepicker works, only recurrence.

Any help please?
