### ISSUE TITLE
Form Widget DtStart

### ISSUE THREAD

**Issue by chinochao** [django-recurrence/django-recurrence#156]
I am having the following issue, not sure if there is some solution but I did not find anything on the documentation.

Here is the issue:
Lets say this month has 5 Fridays(days 3, 10, 17, 24, 31) and I want to use Every 2 Weeks in a Rule. My issue is when I select the Rule, how can I specify the dtstart in the form? I want to have the Fridays as 10 and 24 but it seems the Rule saves the 3,17,31. 

Has anyone found this issue before?

**Comment by dominicrodger** [comment]
Closing in favour of #14.
