### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by agenteAND** [django-recurrence/django-recurrence#168]
Hello, getting Uncaught TypeError: Cannot read property 'split' of undefined when select a day with monthly freq. in admin widget.
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at recurrence.DateFormat.S (recurrence.js:451)
    at recurrence.DateFormat.<anonymous> (recurrence.js:303)
    at recurrence.js:906
    at Object.foreach (recurrence.js:877)
    at recurrence.DateFormat.format (recurrence.js:301)
    at Object.format (recurrence.js:837)
    at recurrence.js:158
    at Object.foreach (recurrence.js:877)
    at recurrence.Rule.get_display_text (recurrence.js:146)
    at recurrence.widget.RuleForm.get_display_text (recurrence-widget.js:983)
```

**Comment by thimonsn** [comment]
I was having the same issue. Looking at the recurrence.js file below, recurrence.langauage_code was always being set to undefined. Not sure why... but to solve, I changed line 448 to "var language_code = 'en-us'" and this solved the problem for me. This matched the language code that was in my Settings.py file.

You can quickly test this by setting recurrence.langauge_code to "en-us" in the inspect tool. and then seeing if the error is thrown. 

This probably isn't the best solution but it worked for me and I didn't want to waste too much time on this issue.

![Capture](https://user-images.githubusercontent.com/14133861/93691582-12396f80-fab5-11ea-9400-0c38a682f005.PNG)

**Comment by SteveHere** [comment]
Still have the same problem; here's a fix for anyone else:
`
            <script>
                setTimeout(function(){
                    (function(elements){
                        if(elements.length > 0){ elements[0].id = "container" }
                    })(document.getElementsByClassName('recurrence-widget'));
                    // This line is needed to resolve this bug: https://github.com/django-recurrence/django-recurrence/issues/168
                    recurrence.language_code = "en";
                }, 10);
            </script>
            `

**Comment by agenteAND** [comment]
> Aun tengo el mismo problema; aquí hay una solución para cualquier otra persona:
> 
> ```
> 
> <script>
>     setTimeout(function(){
>         (function(elements){
>             if(elements.length > 0){ elements[0].id = "container" }
>         })(document.getElementsByClassName('recurrence-widget'));
>         // This line is needed to resolve this bug: https://github.com/django-recurrence/django-recurrence/issues/168
>         recurrence.language_code = "en";
>     }, 10);
> </script>
> ```

        recurrence.language_code = "en";  fix this bug thanks @SteveHere

**Comment by SteveHere** [comment]
The bug is still not resolved. The developer shouldn't need to set `language_code` to `en`.
