### ISSUE TITLE
Widget wrong visualization with django-recurrence + django-admin-bootstrap

### ISSUE THREAD

**Issue by Seether85** [django-recurrence/django-recurrence#34]
As per title, when trying to use the two together, I obtain this:

![1](https://cloud.githubusercontent.com/assets/8349902/5503381/86e3e47c-8776-11e4-8e01-def258a9d0d4.png)
![2](https://cloud.githubusercontent.com/assets/8349902/5503382/86f20ebc-8776-11e4-85a6-216a56a5ffec.png)

Basically, the widget is rendered *under* the other parts of the form, and I'm unable to fix it without messing up with the css code... I don't know if I'd rather ask django-admin-bootstrap developers, but I hope you can point me somewhere with this. Thank you for your help!

**Comment by Seether85** [comment]
Just in case anyone else is interested.
Here you can find my open-to-improvements solution: https://github.com/douglasmiranda/django-admin-bootstrap/issues/59

**Comment by dominicrodger** [comment]
Marking as closed - I'm open to re-considering this, but for now, let's just ensure django-recurrence works with the vanilla admin, rather than the various admin skins.
