### ISSUE TITLE
Programmatically create recurrences

### ISSUE THREAD

**Issue by dentemm** [django-recurrence/django-recurrence#38]
I really like this project, but for my requirement I would also need the possibility to create some recurrences programmatically. I cannot seem to figure out how to create the recurrences attribute of a Course instance (example from your docs) by code. 

Could you make a short addition to the docs on how to do this? Thanks!

Update:
I figured it out by looking into your tests. I will just add the steps should anyone be interested:

1. Create a base.Rule object 
2. Create a base.Recurrence object, and add the created Rule object to the rules attribute
3. Assign the Recurrence object to the recurrences attribute of a Course (see doc example)

**Comment by dominicrodger** [comment]
Hey @dentemm - sorry for taking a few days to reply. Did you close this because you figured out how to do it, or for some other reason?

**Comment by dentemm** [comment]
Hi Dominic,

thanks for replying, I closed the issue because I found the solution. Don’t worry about it, I learned a lot by looking into your code! Thank for the project. 

I also edited my issue to include the solution for other people. 

Best regards,

Tim

**Comment by dentemm** [comment]
I found out how to do it, I also updated my initial post to include the solution for other people. Thanks for the project!

**Comment by dominicrodger** [comment]
Ah - awesome, sorry I missed your original edit. I'll re-open this actually - maybe we could improve the documentation, to save people from having to dig into the tests in future.

**Comment by dentemm** [comment]
Alright, good point.
