### ISSUE TITLE
Recurrence model filter

### ISSUE THREAD

**Issue by ghiotion** [django-recurrence/django-recurrence#41]
I have an event model that has a start and end time as well as a RecurrenceField, which is not required (not all events have recurrences).  I've looked at the documentation and the tests, but it's not clear how one would get all recurrences for all event models without checking every event object for its recurrences.  Is it possible to do something like this:

    for item in Event.objects.filter(start__range=(start, end), recurrences=recurrences.between(start, end, dtstart=start, inc=True)):
        //do something with event

**Comment by dominicrodger** [comment]
There's not a better way of doing it than just checking every event object unfortunately, and I'm not sure anything we could build would be any more efficient than that anyway. If others have ideas for how to do better than that, they'd be very welcome, but I can't think of any.

**Comment by ghiotion** [comment]
Thanks, that was the conclusion I reached, but I figured I'd ask.  One idea I had was using a boolean has_recurrence on the model (unless there's a way to check for recurrence - I didn't see one).  At least that way, you'll only need to check the objects that actually have a recurrence.  

Thanks for the response.

**Comment by dominicrodger** [comment]
If your recurrence object on your model is called ``foo``, you should be able to do something like:

    Course.objects.filter(foo__isnull=False)

to find objects with a recurrence object set. Let me know if you have trouble getting that to work, and I'll double-check I've got that right (I don't have a convenient Django shell to test with right now).

**Comment by ghiotion** [comment]
Yep, that seems to work.  Appreciate it.

**Comment by dominicrodger** [comment]
Great - closing this for now.

**Comment by japrogramer** [comment]
hmm, is there a better way to filter for objects now?
instead of iterating one by one to check their occurrence?

I have a potentially a lot of events that would make this approach not feasible.

**Comment by dominicrodger** [comment]
Nope, that's currently the only way, though pull requests welcome if you can think of a way to do this better.
