### ISSUE TITLE
Use DateField instead DateTimeField

### ISSUE THREAD

**Issue by V1ce** [django-recurrence/django-recurrence#53]
Hi,

Thanks for this app really usefull, i use it for an event app.

The problem is i dont need time with my date, that just contrain me to do more loop for find  events, i have try to change DateTimeField to DateField in models.py at line 8,9,25 and 36. After that i delete and recreate reccurence field im my events models, but i always get a DateTimeField.

my views and templates for exemple, i have a list of category that event match the date : 

views : 

    def get_date1(request,date):
        categ_array = []

        eventDate = datetime.strptime(date,'%Y-%m-%d').date()
    
        date_categ = Category.objects.all()
    
        for categ in date_categ:
            try: 
                getEvent = categ.event_set.all(is_cancelled=False)
            
                for event in getEvent:
                    for occ in event.recurrences.occurrences():
                        if occ.date() == eventDate:
                            if categ not in categ_array:
                                categ_array.append(categ)
            except:
                pass
        return render(request, 'agenda/date1.html', locals())
templates : 

    {% for categ in categ_array %}

            <h2>{{categ.name}}</h2>

            {% for event in categ.getEvent %}

                {%for i in event.recurrences.occurrences%}

                    {% if i.date = eventDate %}

                      <li> {{event.title}}</li>

                    {% endif %}

                {% endfor %}

            {% endfor %}

        {% endif %}

    {% endfor %}

As you see i have to test "for i in event.recurrences.occurrences, if i.date = eventDate", if havent this Time field i could just do  "if eventDate in event.recurrences.occurrences" i think my app can be more fast like that.

Thanks for your help

**Comment by dominicrodger** [comment]
Hi @V1ce,

Glad you found django-recurrence useful. I'm not sure we can help you without seeing your models - how do events link to categories?

I don't think we'll be making changes to switch our DateField to DateTimeField - in future it might be nice to have recurrences that are time-based as well as date-based (e.g. do something every 3 hours). I'd be extremely surprised if any performance issues you're seeing are related to the fact that we're using a DateField (though do let us know if you can prove otherwise).

One general comment - it looks to me like you're doing quite a bit of business logic in templates, which is generally a bad idea (particularly given you're duplicating that logic in Python somewhere) - you'd be better off having that be part of the model (possibly the category model, though it's hard to know what you're trying to do without seeing your models file in more detail).

Thanks,

Dom

**Comment by V1ce** [comment]
i dont really got performance problem, its in my head :p, i just think if i do more test for get my events my request its a little more long but no problems.

For my model, i just have category and Event with foreignKey to Category, my app work like this : 

- I have a simple jquery datepicker in my pages, when i click on a date i go to my diary page with a parameter date like this "2015-09-21" at this url 

url(r'^(?P<date>[\d-]+)$', 'get_date1', name='get_date'),

- In my templates i wont have to deal with all category, i just want an array with categroy that have event for this date, thats contrain me to do so many test in templates and i dont like this, so i deal with that in my vieuw as you can see.

models : 

    class Category(models.Model):
        name = models.CharField(_('title'), max_length=100)
        slug = models.SlugField(_('slug'), unique=True)

        def __str__(self):
            return u'%s' % self.name
        class Meta:
            verbose_name = _('Category')
            ordering = ['name']       
        def getEvent(self):     
            return self.event_set.all().filter(is_cancelled = False)

    class Event(models.Model):
        title = models.CharField(_('title'), max_length=100,unique=True)
        slug = models.SlugField(_('slug'), unique=True,null = True, blank = True)
        recurrences = RecurrenceField(null = True, blank = True)
        description = RichTextField(null=True, blank = True)
        is_cancelled = models.BooleanField(_('Cancelled?'), default=False, blank=True)
        clickable =  models.BooleanField(_('Clickable?'), default=False, blank=True)
        category = models.ForeignKey('Category',blank = True,null=True)
        def __str__(self):
            return u'%s' % self.title

        class Meta:
            verbose_name = _('Event')
     
Thanks

**Comment by V1ce** [comment]
After more tests i think this app can't help me anyway :(

unfortunately if i want create a rule , it begin at the current date, my need is to enter a date and add reccurence on it... Dont't see it during my test yesterday because i using the current date ^^

Bye

**Comment by dominicrodger** [comment]
OK, thanks @V1ce.

**Comment by V1ce** [comment]
Just a last question. We can use an end date for the recurrence, why not a start date?

**Comment by V1ce** [comment]
I have find how to make recurrences with a start date simply with the docs... : 

    from datetime import datetime
    import recurrence


    myrule = recurrence.Rule(
        recurrence.DAILY
    )

    pattern = recurrence.Recurrence(
        dtstart=datetime(2015, 10, 2, 0, 0, 0),
        dtend=datetime(2015, 10, 9, 0, 0, 0),
        rrules=[myrule, ]
    )

It thats i want, i got an event started a 2october with daily recurences to 9 october, i check to python dateutil and its easy to do this directly with it too. In your app i really enjoy the admin widget, my users can easy enter complex recursive events with it, but if they can't set a start date will difficult,why we can't have a dtstart on it?
