### ISSUE TITLE
Warning:  RemovedInDjango110Warning: SubfieldBase has been deprecated

### ISSUE THREAD

**Issue by edelvalle** [django-recurrence/django-recurrence#62]
When runing this package with Django 1.9.1 I'm getting the warning:

```
RemovedInDjango110Warning: SubfieldBase has been deprecated. 
Use Field.from_db_value instead.
```

Because the field:

```python
class RecurrenceField(with_metaclass(SubfieldBase, fields.Field)):
    """
    Field that stores a `recurrence.base.Recurrence` object to the
    database.
    """
```

Extends the `SubfieldBase`.

**Comment by dominicrodger** [comment]
Fixed with #63 - thanks for all the hard work here @edelvalle.

@emperorcezar - can you release 1.3.0 when you get a moment?

**Comment by emperorcezar** [comment]
K. 1.3.0 released.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by edelvalle** [comment]
@emperorcezar 1.3.0 was released but just for Python 2, take a look: https://pypi.python.org/simple/django-recurrence/

**Comment by emperorcezar** [comment]
Thanks. Taking a look. Using twine to upload for the first time.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by emperorcezar** [comment]
K. Uploaded the sdist

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by edelvalle** [comment]
Thanks!

**Comment by dominicrodger** [comment]
Marking closed. Thanks @edelvalle and @emperorcezar :+1:
