### ISSUE TITLE
Update tested version

### ISSUE THREAD

**Issue by dominicrodger** [django-recurrence/django-recurrence#64]
Currently, tox.ini has:

    envlist = {py26}-{14,15,16},{py27}-{14,15,16,17},{py33,py34}-{15,16,17},docs,flake8

We should probably drop official support for Python 2.6 entirely, and start testing Django 1.8 and 1.9. We should also probably stop testing Django 1.4-1.7, since those are also EOL (see [the docs](https://www.djangoproject.com/download/#supported-versions)). We should also start testing with Python 3.5.

This will help with work on #63.

**Comment by dominicrodger** [comment]
Partially addressed by ff64fb8 - I still need to add tests for Django 1.9, and Python 3.5.

**Comment by dominicrodger** [comment]
All set. I believe tox doesn't support Python 3.5 at present, so we'll leave this for now - we've got tests for Django 1.9 in, thanks to @edelvalle's work on #62.

**Comment by edelvalle** [comment]
It does not, but when it does, py35 can be added to the tox file.

**Comment by dominicrodger** [comment]
Yup - thanks @edelvalle (my "I believe" should really have been written as "@edelvalle tells me" :)).
