### ISSUE TITLE
Recurrence.between() doesn't exclude Feb 29th when Recurrence has empty dtstart and inclusion is Daily

### ISSUE THREAD

**Issue by alextreme** [django-recurrence/django-recurrence#65]
The following failing test describes the issue:

https://github.com/django-recurrence/django-recurrence/compare/master...alextreme:feb29-exclusion?expand=1

It's an edge-case that only occurs with between() when the Recurrence is daily and the exclusion is Feb 29th and dtstart isn't filled in.

I've been able to easily work around it by either setting dtstart or providing an alternative exclusion rule, but I'm noting this issue in case anyone else stumbles upon it (today or over 4 years).

**Comment by dominicrodger** [comment]
Thanks for the report @alextreme!

I'm not entirely sure that this is a leap year bug - your test passes for me whether the date under test is February 29th or February 28th, as far as I can tell. Was the last assert failing or passing for you? If it was failing, then maybe there is a leap year bug which only shows up when the current date is February 29th.

**Comment by alextreme** [comment]
Thanks for taking a look. The last assert was failing for me on the 29th but now only fails if I update the test to the current date. It has to do with the automatic usage of now() when dtstart isn't given and isn't related to Feb 29th. 

This seems similar to the remark on https://django-recurrence.readthedocs.org/en/latest/usage/recurrence_field.html

"Slightly confusingly, between will only return you dates after the current date, if used as above"

And slightly later:

"Without dtstart, we implicitly are looking for occurrences after the current date."

Odd behaviour (I'd expect the current date to be included) but it was clearly documented and easy to work around so I'll close this issue.
