### ISSUE TITLE
Specify BiWeekly start date of a recurrence?

### ISSUE THREAD

**Issue by somesmart** [django-recurrence/django-recurrence#66]
I'm trying to schedule a biweekly recurrence (every other Friday), but it seems to set the starting Friday automatically? Is it possible to specify the Friday it starts on and I'm just missing it?

**Comment by dominicrodger** [comment]
Hey @somesmart. How are you generating recurrences? Via with widget? Via the API? If the latter, have you set ``dtstart`` (see [here](http://django-recurrence.readthedocs.org/en/latest/usage/api.html#rule-and-recurrence) for details)?

**Comment by somesmart** [comment]
I was creating them via the widget. Is there a way to set the `dtstart` from there or do I need to do it on form save?

**Comment by dominicrodger** [comment]
Ah, yeah, you need to set it on form save, you can't set ``dtstart`` from the widget.

**Comment by somesmart** [comment]
That did it, thanks!
