### ISSUE TITLE
Finding all generated occurrences of model

### ISSUE THREAD

**Issue by bodgerbarnett** [django-recurrence/django-recurrence#68]
I am using this to generate a range of instances of a model (Event) based on the rules set at creation time but I want the form that produces them to redirect to a page which lists all the generated occurrences, once they've been created.

Is there an easy way to do this or do I have to manage it myself using a new model to connect them all or something maybe?

I was kind of hoping I could do something like

`event.recurrences.instances()`

to get hold of them.

Or is this something I would have to manage myself?

**Comment by dominicrodger** [comment]
I think you can just use `occurrences`, as per [the docs](http://django-recurrence.readthedocs.io/en/latest/usage/recurrence_field.html#getting-all-occurrences), or does that not work for you?

**Comment by bodgerbarnett** [comment]
Unfortunately, that only returns the dates that the recurrence pattern contains, not the instances of the model that was created with it.

**Comment by dominicrodger** [comment]
Oh, I see. I think that's out of scope - django-recurrence has no idea what models you created with a `Recurrence` object, and I'm not sure how it could know. If you've got a recurrence object stored on a model somewhere, then perhaps you could use the model instance used to create them on your `Event` model.

**Comment by bodgerbarnett** [comment]
At the moment, I've got it set on the Event model.

So you mean I could have the recurrence field on a new model - EventGroup, say? And then have a foreign key to that model on Event so that I could get all the events that are connected that way?

That makes sense and I think (ahem) that that was what I was hinting at when I said "manage myself". Maybe. But if that's what you mean, thanks.

**Comment by dominicrodger** [comment]
I think I need to see your models to understand exactly what you're doing. If you're creating lots of Events at once, then you could tie them together using a GUID field on the Event (where each instance created from a single recurrence has the same GUID), that might be simpler than having a separate EventGroup model or similar.

In brief though, you'll definitely have to handle this yourself.

**Comment by bodgerbarnett** [comment]
Ah, good thinking - that's excellent - thanks!
