### ISSUE TITLE
Does not work with Django 1.10

### ISSUE THREAD

**Issue by ondrowan** [django-recurrence/django-recurrence#69]
`fields.py` still uses `Creator` from `django.db.models.fields.subclassing` which is removed in Django 1.10.

**Comment by dominicrodger** [comment]
Thanks for filing this @ondrowan - I've just pushed a fix (basically pulling `Creator` into django-recurrence for versions of Django which don't have it).

**Comment by oliwarner** [comment]
@dominicrodger Probably not the right place to ask but I see this is in the changelog for 1.4 on RDT but I can't find 1.4 on pypi. Has this not been released yet?

**Comment by dominicrodger** [comment]
Yep - this is tracked in #72. Sadly, I don't have privs to push a new version to PyPI.

**Comment by emperorcezar** [comment]
Gonna put in some time this weekend and do the push.
