### ISSUE TITLE
Version 1.4.0 not available on pypi

### ISSUE THREAD

**Issue by dodobas** [django-recurrence/django-recurrence#72]
Is 1.4.0 planned to be released soon, Django 1.10 was released on August, 1st and the current version 1.3.0 is not compatible.

**Comment by emperorcezar** [comment]
I'll push it out today.

**Comment by dodobas** [comment]
hopefully 'today' is today :)

**Comment by jordanambra** [comment]
@emperorcezar can you do this push to pypi? All of my apps are on Django 1.10+ and I can't install without using pip+git.

**Comment by emperorcezar** [comment]
@jordanambra @dodobas Today became later than I thought mostly because pypi giving my issues, but it's out as of now.

**Comment by jordanambra** [comment]
Thank you!
