### ISSUE TITLE
Javascript widget not working.

### ISSUE THREAD

**Issue by adlius** [django-recurrence/django-recurrence#76]
I am using django-recurrence for a project. When I try to use the javascript widget for the form, it does not render correctly in the browser (both safari and chrome). Here's the screen shot
<img width="305" alt="screen shot 2016-10-24 at 12 44 18" src="https://cloud.githubusercontent.com/assets/1566880/19654776/b327a26e-99e7-11e6-8456-c1cb1582e38c.png">

And here's the snippet for the html:
<img width="562" alt="screen shot 2016-10-24 at 12 49 26" src="https://cloud.githubusercontent.com/assets/1566880/19654960/5a6733dc-99e8-11e6-83e8-a39f974f739a.png">

I am pretty sure the the static assets are loading correctly cuz the terminal prints out the static assets requests and it is serving the assets correctly.

**Comment by dominicrodger** [comment]
Hi @adlius - I'm afraid we'll need more information to figure out what's going wrong. Are there any JavaScript errors? What's the output of that template? Are you sure the browser is managing to load the CSS/JS? What version of django/django-recurrence/Python are you using?

**Comment by dominicrodger** [comment]
Marking closed for now, feel free to re-open if you need help here @adlius.

**Comment by wolfhound115** [comment]
Hey I'm actually having the exact same problem. No errors just the widget doesnt work in my Model Forms in the exact same way as pictured above. Was anyone able to resolve the issue?
