### ISSUE TITLE
Wagtail Compatibility: "Uncaught ReferenceError: pgettext is not defined at recurrence.js:1036"

### ISSUE THREAD

**Issue by FlipperPA** [django-recurrence/django-recurrence#99]
I'm trying to get this working with the Wagtail CMS. I've got a basic Wagtail model - a Wagtail `Page` inherits from a Django `models.Model`:

```
class Event(Page):
    """
    Model for storing recurring events.
    """

    description = models.TextField()
    start = models.TimeField()
    end = models.TimeField()
    recurrences = recurrence.fields.RecurrenceField()

    content_panels = Page.content_panels + [
        FieldPanel('description'),
        FieldPanel('start'),
        FieldPanel('end'),
        FieldPanel('recurrences'),
    ]

    def __str__(self):
        return '{0}'.format(
            self.title,
        )
```

Many fields which "work" in the Django admin also work in the Wagtail admin. However, I'm getting the following JavaScript error:

```
recurrence.js:1036 Uncaught ReferenceError: pgettext is not defined at recurrence.js:1036
```

As you can see from the screenshot, it does partially instantiate:

![image](https://user-images.githubusercontent.com/68164/30288132-a11bc814-96f5-11e7-91c6-71a29283d4f4.png)

Clicking "Add Rule" gives the following error:

```
recurrence-widget.js:1122 Uncaught TypeError: Cannot read property '0' of undefined
    at recurrence.widget.RuleYearlyForm.init_dom (recurrence-widget.js:1122)
    at recurrence.widget.RuleYearlyForm.init (recurrence-widget.js:1108)
    at recurrence.widget.RuleYearlyForm (recurrence-widget.js:1101)
    at recurrence.widget.RuleForm.<anonymous> (recurrence-widget.js:961)
    at recurrence.js:905
    at Object.foreach (recurrence.js:876)
    at recurrence.widget.RuleForm.init_dom (recurrence-widget.js:958)
    at recurrence.widget.RuleForm.init (recurrence-widget.js:732)
    at recurrence.widget.RuleForm (recurrence-widget.js:710)
    at recurrence.widget.Widget.add_rule_panel (recurrence-widget.js:533)
```

I realize this is not what `django-recurrence` was initially designed for, but it'd be great if we could get this working as well. I figured I'd start an issue in case anyone had experience getting this to work with Wagtail, or could point me in the right direction as I start digging. Thank you!

**Comment by FlipperPA** [comment]
Thanks to some help from Torchbox, I've got this working. It can use some CSS tweaks, but the key was to include the jsil8n library:

```
import recurrence.fields
import datetime

from django.db import models

from wagtail.wagtailcore import hooks
from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import FieldPanel


class Event(Page):
    """
    Model for storing recurring events.
    """

    description = models.TextField()
    start = models.TimeField()
    end = models.TimeField()
    recurrences = recurrence.fields.RecurrenceField()

    content_panels = Page.content_panels + [
        FieldPanel('description'),
        FieldPanel('start'),
        FieldPanel('end'),
        FieldPanel('recurrences'),
    ]

    def __str__(self):
        return '{0}'.format(
            self.title,
        )


@hooks.register('insert_editor_js')
def editor_js():
    return '<script src="/admin/jsi18n/"></script>'
```

Hopefully this helps the next person looking!

![image](https://user-images.githubusercontent.com/68164/30289720-12c5c0be-96fb-11e7-8b6a-cc556309f83e.png)

**Comment by gabrielwolf** [comment]
On Wagtail 2.4 I have problems. I can't load `<script src="/admin/jsi18n/"></script>`. Chrome says `http://0.0.0.0:8000/admin/jsi18n/ 404 (Not Found)`.

My base.py settings have `USE_I18N = True` and `USE_L10N = True`.

Any help greatly appreciated!
Gabriel

**Comment by FlipperPA** [comment]
Howdy @gabrielwolf, what URL do you have the Django Admin mapped to? I know with Wagtail, it is a common pattern to map the Wagtail admin to `/admin/` and the Django admin to `/django-admin/`. The JS file comes from the Django admin, so if you have it mapped at `/django-admin/`, then you're need to change the code to: `<script src="/django-admin/jsi18n/"></script>`. Does that make sense?

**Comment by gabrielwolf** [comment]
Thanks @FlipperPA You helped me out 👍

**Comment by Jean-Zombie** [comment]
@gabrielwolf 
may I ask if you got it to work? I followed all steps in this thread including the `django-admin` url part but my console throws me this error:
`TypeError: django.jQuery is not a function` for the first line of the `recurrence-widget.init.js`. This seems to be very basic but I am noob. JQuery loads correctly though…

**Comment by tobiasgoecke** [comment]
+1
